usethis::use_build_ignore("_devhistory.R")
usethis::use_git(message = ":tada: Initial commit")
usethis::use_git_ignore(".DS_Store")
usethis::use_build_ignore(".DS_Store")
usethis::use_git(message = ":see_no_evil: Ban .DS_Store files")
usethis::edit_file("DESCRIPTION")
usethis::use_git(message = ":bulb: Edit package metadata")
usethis::use_package_doc()
devtools::document()
usethis::use_mit_license(name = "Nicolas Casajus")
usethis::use_r("cb_taxa_gene")
devtools::load_all()
usethis::use_git(message = ":boom: New fonctio - cb_taxa_gene")
